Algoritmo "media_tres_numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2024
Var
// Seção de Declarações das variáveis 
soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma <- (5 + 3 + 5) / 2

escreval("A média da soma é: ", soma)

Fimalgoritmo