Algoritmo "TipoDados"

Var
nome: caractere
idade: inteiro
altura: real
crianca: caractere

Inicio
escreva("Digite seu nome: ")
leia(nome)

escreva("Digite sua idade: ")
leia(idade)

escreva("Digite sua altura: ")
leia(altura)

escreva("Você é uma criança? ")
leia(crianca)

escreval("Nome: ", nome)
escreval("Idade: ", idade)
escreval("Altura: ", altura)
escreval("É uma criança? ", crianca)

Fimalgoritmo